image: docker

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_scripts:
  - apk add --no-cache openssh
  - apk add --no-cache openssh-client
  - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H 'limelightapp.ml' >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - docker version
  - docker-compose version

buildJob:
  stage: build
  tags:
    - docker
  script:
    - docker-compose -f docker-compose.ci.yml build
    - docker login registry.gitlab.com -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker-compose -f docker-compose.ci.yml push

testJob:
  stage: test
  tags:
    - docker
  script:
    - docker-compose -f docker-compose.ci.yml pull
    - docker-compose -f docker-compose.ci.yml run app-test

deployJob:

  stage: deploy
  tags:
    - docker
  script:
    - ssh jigel@limelightapp.ml "docker-compose -f docker-compose.ci.yml pull;docker-compose -f docker-compose.ci.yml run app"