image: tmaier/docker-compose:latest

stages:
  - build
  - test

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

buildJob:
  stage: build
  tags:
    - docker
  script:
    - docker-compose -f docker-compose.ci.yml build
    - docker login registry.gitlab.com -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker-compose -f docker-compose.ci.yml push

testJob:
  stage: test
  tags:
    - docker
  script:
    - docker-compose -f docker-compose.ci.yml pull
    - docker-compose -f docker-compose.ci.yml run app-test