image: tmaier/docker-compose:latest

stages:
  - build
  - test
  - deploy

services:
  - docker:dind  

buildJob:
  stage: build
  tags:
    - docker
  script:
    - docker-compose -f docker-compose.ci.yml build
    - apk update && apk add git
    - echo $REGISTRY_PASS | docker login registry.gitlab.com -u $REGISTRY_USER --password-stdin
    - docker-compose -f docker-compose.ci.yml push
    - git checkout production
    - git fetch
    - docker-compose -f docker-compose.ci.prod.yml build
    - docker-compose -f docker-compose.ci.prod.yml push

testJob:
  stage: test
  tags:
    - docker
  script:
    - docker-compose -f docker-compose.ci.yml pull
    - docker-compose -f docker-compose.ci.yml run --rm app-test

deployJob:
  stage: deploy
  only:
    - production
  tags:
    - docker
  script:
    - apk add --no-cache openssh
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 'limelightapp.ml' >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -v ci@limelightapp.ml "rm -rf limelight_api && git clone git@gitlab.com:mirandajyothy/limelight_api.git && cp .env limelight_api/.env && cd limelight_api && docker-compose -f docker-compose.deploy.yml pull && docker-compose -f docker-compose.deploy.yml up -d app" || ssh -v ci@limelightapp.ml "rm -rf limelight_api && git clone git@gitlab.com:mirandajyothy/limelight_api.git && cp .env limelight_api/.env && cd limelight_api && docker-compose -f docker-compose.deploy.yml pull && docker-compose -f docker-compose.deploy.yml up -d app" || ssh -v ci@limelightapp.ml "rm -rf limelight_api && git clone git@gitlab.com:mirandajyothy/limelight_api.git && cp .env limelight_api/.env && cd limelight_api && docker-compose -f docker-compose.deploy.yml pull && docker-compose -f docker-compose.deploy.yml up -d app"