version: "3"
services:

  pyml:
    container_name: pyml
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - FLASK_ENV=production
    image: registry.gitlab.com/mirandajyothy/limelight_api/limelight_api_pyml:latest-prod
    networks:
      - mainnet

  app:
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    image: registry.gitlab.com/mirandajyothy/limelight_api/limelight_api_app:latest-prod
    environment:
      - APP_ENV=production
    ports:
      - "8080:8080"
    networks:
      - mainnet
    depends_on:
      - mongo
      - pyml
      - redis
      
  app-test:
    container_name: api-test
    restart: "no"
    env_file:
      - .env
    environment:
      - APP_ENV=test
    image: registry.gitlab.com/mirandajyothy/limelight_api/limelight_api_app_test:latest-prod
    networks:
      - mainnet
    depends_on:
      - mongo
      - pyml
      - redis
  
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo:4.1
    env_file:
      - .env
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mainnet

  redis:
    container_name: redis
    restart: unless-stopped
    image: 'bitnami/redis:5.0-debian-9'
    command: /run.sh --maxmemory 100mb --maxmemory-policy allkeys-lru
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/bitnami/redis/data
    networks:
      - mainnet    

networks:
  mainnet:

volumes:
  mongodata:
  redisdata:
  